export const majors = [
  {
    code: "TKJ",
    name: "Teknik Komputer dan Jaringan",
    icon: "Network",
    description:
      "Teknik Komputer dan Jaringan mempersiapkan siswa dalam bidang jaringan komputer, teknologi informasi, server, perangkat jaringan, dan IT Support.",
    careers: ["IT Support", "Teknisi Jaringan", "Network Administrator"],
  },
  {
    code: "RPL",
    name: "Rekayasa Perangkat Lunak",
    icon: "Code2",
    description:
      "Rekayasa Perangkat Lunak mempersiapkan siswa dalam pengembangan website, aplikasi, software, dan pemrograman.",
    careers: ["Web Developer", "Software Developer", "Programmer"],
  },
  {
    code: "DKV",
    name: "Desain Komunikasi Visual",
    icon: "Palette",
    description:
      "Desain Komunikasi Visual mengembangkan kemampuan siswa dalam desain grafis, branding, ilustrasi, fotografi, dan industri kreatif.",
    careers: ["Graphic Designer", "Illustrator", "Content Designer"],
  },
  {
    code: "Animasi",
    name: "Animasi",
    icon: "Clapperboard",
    description:
      "Program Animasi mengembangkan kemampuan dalam animasi 2D, 3D, motion graphic, multimedia, dan produksi kreatif.",
    careers: ["Animator", "Motion Designer", "3D Artist"],
  },
  {
    code: "Tata Boga",
    name: "Tata Boga",
    icon: "ChefHat",
    description:
      "Mengembangkan keterampilan dalam pengolahan makanan, pastry, bakery, restoran, catering, dan industri kuliner.",
    careers: ["Chef", "Pastry Cook", "Catering Professional"],
  },
  {
    code: "Perhotelan",
    name: "Perhotelan",
    icon: "Hotel",
    description:
      "Mempersiapkan siswa dalam bidang hospitality, front office, housekeeping, food and beverage, hotel, dan pelayanan tamu.",
    careers: ["Front Office", "Housekeeping", "Food & Beverage"],
  },
] as const;

export const achievements = [
  {
    title: "Juara 1 Web Technologies",
    field: "Lomba Kompetensi Siswa",
    year: "2026",
    person: "Tim RPL",
    icon: "Code2",
  },
  {
    title: "Gold Medal Desain Poster",
    field: "Festival Kreativitas Pelajar",
    year: "2025",
    person: "Nadia Putri",
    icon: "Award",
  },
  {
    title: "Juara Favorit Film Animasi",
    field: "Festival Film Pelajar",
    year: "2025",
    person: "Tim Animasi",
    icon: "Clapperboard",
  },
] as const;

export const graduates = [
  {
    name: "Alya Ramadhani",
    major: "RPL",
    year: "2024",
    achievement: "Junior Web Developer",
    initials: "AR",
  },
  {
    name: "Raka Pratama",
    major: "TKJ",
    year: "2023",
    achievement: "Network Support Specialist",
    initials: "RP",
  },
  {
    name: "Dinda Maharani",
    major: "Tata Boga",
    year: "2024",
    achievement: "Pastry Entrepreneur",
    initials: "DM",
  },
] as const;

export const news = [
  {
    date: "18 Agustus 2026",
    category: "Kegiatan",
    title: "Semangat Kemerdekaan dalam Karya Siswa",
    excerpt: "Kolaborasi lintas jurusan menghadirkan karya kreatif bertema budaya dan teknologi.",
  },
  {
    date: "12 Agustus 2026",
    category: "Sekolah",
    title: "Pembekalan Siswa Menuju Dunia Industri",
    excerpt: "Siswa memperoleh penguatan etika kerja, komunikasi, dan kesiapan kompetensi.",
  },
  {
    date: "5 Agustus 2026",
    category: "Prestasi",
    title: "Karya Digital Siswa Raih Apresiasi",
    excerpt: "Proyek digital siswa mendapat apresiasi dalam gelar karya tingkat pelajar.",
  },
] as const;

export const partners = [
  "Mitra Teknologi",
  "Mitra Industri Kreatif",
  "Mitra Hospitality",
  "Mitra Kuliner",
  "Mitra Pendidikan",
] as const;

export const products = [
  {
    id: "website-umkm",
    name: "Paket Website UMKM",
    category: "Layanan Digital",
    description: "Layanan pembuatan website profil usaha yang responsif dan mudah dikelola.",
    price: "Mulai Rp750.000",
    unit: "RPL",
    icon: "Laptop",
  },
  {
    id: "branding-kit",
    name: "Creative Branding Kit",
    category: "Desain",
    description: "Paket identitas visual berisi logo, warna, dan materi promosi dasar.",
    price: "Mulai Rp350.000",
    unit: "DKV",
    icon: "Palette",
  },
  {
    id: "kue-premium",
    name: "Kue Kering Premium",
    category: "Kuliner",
    description: "Kue kering hasil praktik produksi dengan pilihan rasa yang beragam.",
    price: "Rp65.000",
    unit: "Tata Boga",
    icon: "Cookie",
  },
  {
    id: "motion-package",
    name: "Motion Graphic Package",
    category: "Kreatif",
    description: "Layanan video motion graphic singkat untuk informasi dan promosi.",
    price: "Hubungi Kami",
    unit: "Animasi",
    icon: "Play",
  },
  {
    id: "network-audit",
    name: "Pemeriksaan Jaringan",
    category: "Teknologi",
    description: "Pemeriksaan dasar jaringan lokal dan dokumentasi perangkat.",
    price: "Hubungi Kami",
    unit: "TKJ",
    icon: "Wifi",
  },
  {
    id: "table-service",
    name: "Table Service Training",
    category: "Hospitality",
    description: "Paket latihan layanan meja untuk kegiatan dan pelatihan dasar.",
    price: "Hubungi Kami",
    unit: "Perhotelan",
    icon: "ConciergeBell",
  },
] as const;

export type PklStatus = "Sedang Dibuka" | "Pendaftaran Ditutup";
export const pklListings = [
  {
    id: 1,
    company: "Nusa Digital Studio",
    location: "Surabaya",
    field: "Teknologi Informasi",
    majors: ["TKJ", "RPL"],
    position: "IT Support & Web Developer",
    period: "Januari–Maret 2027",
    requirements: "Siswa kelas XI, CV, portofolio sederhana",
    description: "Program praktik untuk membantu dukungan perangkat dan pengembangan web internal.",
    contact: "Kontak tersedia setelah verifikasi",
    link: "#",
    status: "Sedang Dibuka" as PklStatus,
    type: "PKL",
    updated: "28 Agustus 2026",
  },
  {
    id: 2,
    company: "Kreasi Visual Jatim",
    location: "Malang",
    field: "Industri Kreatif",
    majors: ["DKV", "Animasi"],
    position: "Graphic Designer & Motion Intern",
    period: "Februari–April 2027",
    requirements: "Portofolio desain atau animasi, mampu bekerja dalam tim",
    description: "Kesempatan belajar produksi konten visual, ilustrasi, dan motion graphic.",
    contact: "Kontak tersedia setelah verifikasi",
    link: "#",
    status: "Sedang Dibuka" as PklStatus,
    type: "PKL",
    updated: "26 Agustus 2026",
  },
  {
    id: 3,
    company: "Hospitality Training Center",
    location: "Mojokerto",
    field: "Hospitality",
    majors: ["Perhotelan", "Tata Boga"],
    position: "Front Office & Kitchen Trainee",
    period: "November 2026–Januari 2027",
    requirements: "Komunikatif, disiplin, surat pengantar sekolah",
    description: "Praktik layanan tamu, penataan area, serta pengenalan operasional dapur.",
    contact: "Kontak tersedia setelah verifikasi",
    link: "#",
    status: "Pendaftaran Ditutup" as PklStatus,
    type: "PKL",
    updated: "20 Agustus 2026",
  },
  {
    id: 4,
    company: "Inovasi Network Lab",
    location: "Sidoarjo",
    field: "Infrastruktur IT",
    majors: ["TKJ"],
    position: "Teknisi Jaringan",
    period: "Januari–April 2027",
    requirements: "Dasar jaringan, perangkat jaringan, dan dokumentasi",
    description: "Praktik instalasi, pemeliharaan, dan dokumentasi infrastruktur jaringan.",
    contact: "Kontak tersedia setelah verifikasi",
    link: "#",
    status: "Sedang Dibuka" as PklStatus,
    type: "PKL",
    updated: "30 Agustus 2026",
  },
  {
    id: 5,
    company: "Rasa Nusantara Workshop",
    location: "Kediri",
    field: "Industri Makanan",
    majors: ["Tata Boga"],
    position: "Bakery & Kitchen Trainee",
    period: "Desember 2026–Februari 2027",
    requirements: "Memahami higiene dasar dan pengolahan makanan",
    description: "Praktik produksi bakery, persiapan bahan, dan standar kebersihan dapur.",
    contact: "Kontak tersedia setelah verifikasi",
    link: "#",
    status: "Sedang Dibuka" as PklStatus,
    type: "PKL",
    updated: "25 Agustus 2026",
  },
] as const;

export const careerListings = [
  {
    id: 1,
    company: "Solusi Teknologi Timur",
    position: "Junior Web Developer",
    location: "Surabaya",
    majors: ["RPL"],
    requirements: "HTML, CSS, JavaScript, dan portofolio dasar",
    deadline: "30 September 2026",
    status: "Sedang Dibuka",
  },
  {
    id: 2,
    company: "Visual Karya Studio",
    position: "Junior Graphic Designer",
    location: "Malang",
    majors: ["DKV"],
    requirements: "Portofolio desain grafis dan kemampuan komunikasi visual",
    deadline: "20 September 2026",
    status: "Sedang Dibuka",
  },
  {
    id: 3,
    company: "Jaringan Prima",
    position: "IT Support",
    location: "Sidoarjo",
    majors: ["TKJ", "RPL"],
    requirements: "Dasar troubleshooting komputer dan jaringan",
    deadline: "15 September 2026",
    status: "Sedang Dibuka",
  },
  {
    id: 4,
    company: "Nusantara Hospitality",
    position: "Front Office Staff",
    location: "Banyuwangi",
    majors: ["Perhotelan"],
    requirements: "Komunikatif, rapi, dan berorientasi pada layanan",
    deadline: "10 September 2026",
    status: "Pendaftaran Ditutup",
  },
] as const;

export const locations = [
  "Surabaya",
  "Mojokerto",
  "Sidoarjo",
  "Malang",
  "Gresik",
  "Pasuruan",
  "Kediri",
  "Jember",
  "Banyuwangi",
  "Wilayah Jawa Timur lainnya",
] as const;
